const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info:{
        version: "0.1.0",
        title:"Student Rest API with Swagger",
        description:"Documentation generated by the <b><i>swagger-autogen</i></b> module"
    },
    host:"localhost:3000",
    basePath:"/",
    schemes:["http", "https"],
    consumes:["application.json"],
    produces:["application.json"],
    tags:[
        {
            "name":"Student",
            "description":"Student data"
        }
    ],

    definitions:{
        Student:{
            "id": 1,
            "firstname": "Tom",
            "lastname": 'Clement',
            "classname": "A1",
            "age": 7
        },
        Students:[
            { $ref: "#/definitions/Student" }
        ]
    }
}



const outputFile = './swagger.json';
const endpointsFile = ['./app.js'];

swaggerAutogen(outputFile, endpointsFile, doc).then(()=>{
    require('./app');
})