const swaggerAutogen = require('swagger-autogen')();

const doc = {
    info:{
        version: "0.1.1",
        title:"Student Rest API with Swagger",
        description: "Documentation generated by the <b><i>swagger-autogen</i></b> module"
    },
    host:"localhost:3000",
    basePath:"/",
    schemes:["http", "https"],
    consumes:["application.json"],
    produces:["application.json"],
    tags: [{
            "name": "Student",
            "description": "Student data"
        },
        {
            "name": "Teacher",
            "description": "Teacher data"
        },
        {
            "name": "Lecture",
            "description": "Lecture data"
        }
    ],

    definitions: {
        Student: {
            "id": 1,
            "firstname": "Tom",
            "lastname": 'Clement',
            "classname": "A1",
            "age": 7,
            "Courses": [
                {
                    "name": "History"
                }
            ],
            "Teachers": [
                {
                    "firstname": "Noah",
                    "lastname": "François"
                }
            ]
        },
        Teacher: {
            "id": 1,
            "firstname": "David",
            "lastname": 'Möller',
            "Specialty": "Mathematics"
        },
        Lecture: {
            "id": 1,
            "name": "Mathematics",
            "The Responsible": {
                "firstname": "Emma",
                "lastname": "Durand"
            }
        }
    }
}



const outputFile = './swagger.json';
const endpointsFile = ['./app.js'];

swaggerAutogen(outputFile, endpointsFile, doc).then(()=>{
    require('./app');
})